import { Post } from "./lib/db";

export const posts: Post[] = [
  {
    id: '1',
    title: 'The Art of Clean Code',
    subject: 'Computer Science',
    topic: 'Software Engineering',
    subtopic: 'Best Practices',
    snippet: 'Discover the fundamental principles of writing clean, maintainable, and efficient code that stands the test of time.',
    content: '<p>Clean code is not just about writing code that works. It is about writing code that is easy to read, understand, and maintain. In this post, we will explore the key principles of clean code, including meaningful names, small functions, and avoiding comments when the code can speak for itself.</p><p>As Robert C. Martin says, "Clean code always looks like it was written by someone who cares."</p>',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Ada Lovelace' },
    date: 'Oct 15, 2023',
    featured: true,
    tags: ['Programming', 'Clean Code', 'Best Practices'],
    readTime: '5 min read',
    status: 'published'
  },
  {
    id: '2',
    title: 'Understanding Quantum Computing',
    subject: 'Physics',
    topic: 'Quantum Mechanics',
    subtopic: 'Computing',
    snippet: 'A beginner-friendly introduction to the mind-bending world of quantum computers and how they differ from classical ones.',
    content: '<p>Quantum computers use quantum bits, or qubits, which can exist in multiple states simultaneously thanks to superposition. This allows them to perform certain complex calculations exponentially faster than classical computers.</p><h2>The Power of Entanglement</h2><p>Another key principle is entanglement, where qubits become linked such that the state of one instantly affects the other, regardless of distance.</p>',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Richard Feynman' },
    date: 'Nov 02, 2023',
    featured: false,
    tags: ['Physics', 'Quantum', 'Technology'],
    readTime: '8 min read',
    status: 'published'
  },
  {
    id: '3',
    title: 'The Beauty of Calculus',
    subject: 'Mathematics',
    topic: 'Calculus',
    subtopic: 'Derivatives',
    snippet: 'Explore how calculus helps us understand change and motion in the universe through derivatives and integrals.',
    content: '<p>Calculus is the mathematical study of continuous change. It has two major branches: differential calculus and integral calculus.</p><ul><li><b>Differential Calculus:</b> focuses on rates of change and slopes of curves.</li><li><b>Integral Calculus:</b> focuses on accumulation of quantities and areas under curves.</li></ul>',
    image: 'https://images.unsplash.com/photo-1632516643720-e7f5d7d6eca8?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Isaac Newton' },
    date: 'Nov 12, 2023',
    featured: false,
    tags: ['Math', 'Calculus', 'Science'],
    readTime: '6 min read',
    status: 'published'
  },
  {
    id: '4',
    title: 'Designing Accessible User Interfaces',
    subject: 'Computer Science',
    topic: 'Design',
    subtopic: 'Accessibility',
    snippet: 'Learn why accessibility is crucial in modern web design and how to implement WCAG guidelines effectively.',
    content: '<p>Accessibility (a11y) ensures that digital products are usable by everyone, including people with disabilities. This means designing for screen readers, ensuring sufficient color contrast, and providing keyboard navigation.</p>',
    image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Tim Berners-Lee' },
    date: 'Dec 05, 2023',
    featured: false,
    tags: ['Design', 'UI/UX', 'Accessibility'],
    readTime: '7 min read',
    status: 'published'
  },
  {
    id: '5',
    title: 'The Evolution of Stars',
    subject: 'Physics',
    topic: 'Astrophysics',
    subtopic: 'Stellar Evolution',
    snippet: 'Trace the lifecycle of a star from a collapsing nebula to a white dwarf, neutron star, or black hole.',
    content: '<p>Stars are born in vast clouds of gas and dust called nebulae. Over millions of years, gravity pulls this matter together until nuclear fusion ignites.</p>',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&q=80&w=2049',
    author: { name: 'Carl Sagan' },
    date: 'Jan 18, 2024',
    featured: false,
    tags: ['Astronomy', 'Stars', 'Space'],
    readTime: '10 min read',
    status: 'published'
  },
  {
    id: '6',
    title: 'Introduction to Machine Learning',
    subject: 'Computer Science',
    topic: 'Artificial Intelligence',
    subtopic: 'Machine Learning',
    snippet: 'A comprehensive overview of machine learning concepts, algorithms, and real-world applications.',
    content: '<p>Machine Learning is a subset of AI that allows systems to learn from data without explicit programming. Common algorithms include linear regression, decision trees, and neural networks.</p>',
    image: 'https://images.unsplash.com/photo-1527474305487-b87b222841cc?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Alan Turing' },
    date: 'Feb 10, 2024',
    featured: false,
    tags: ['AI', 'Machine Learning', 'Data Science'],
    readTime: '12 min read',
    status: 'published'
  },
  {
    id: '7',
    title: 'The History of the Internet',
    subject: 'Computer Science',
    topic: 'Networking',
    subtopic: 'History',
    snippet: 'From ARPANET to the World Wide Web, learn how the internet evolved into the global network we know today.',
    content: '<p>The internet began as a military project called ARPANET in the 1960s. It eventually evolved into a global network of interconnected computers communicating via standardized protocols.</p>',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=2072',
    author: { name: 'Vint Cerf' },
    date: 'Mar 01, 2024',
    featured: false,
    tags: ['Internet', 'History', 'Networking'],
    readTime: '9 min read',
    status: 'published'
  },
  {
    id: '8',
    title: 'The Wonders of General Relativity',
    subject: 'Physics',
    topic: 'Relativity',
    subtopic: 'General Relativity',
    snippet: 'Understand Einstein’s theory of general relativity and how it revolutionized our understanding of gravity and space-time.',
    content: '<p>General relativity describes gravity not as a force, but as the curvature of space-time caused by mass and energy. This theory predicted phenomena like black holes and gravitational waves.</p>',
    image: 'https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&q=80&w=2050',
    author: { name: 'Albert Einstein' },
    date: 'Mar 15, 2024',
    featured: false,
    tags: ['Physics', 'Relativity', 'Gravity'],
    readTime: '11 min read',
    status: 'published'
  },
  {
    id: '9',
    title: 'Mastering React Hooks',
    subject: 'Computer Science',
    topic: 'Web Development',
    subtopic: 'React',
    snippet: 'Deep dive into React Hooks like useState, useEffect, and useContext for state management in functional components.',
    content: '<p>React Hooks introduced a way to use state and other React features without writing a class. They make components more reusable and easier to understand.</p>',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Dan Abramov' },
    date: 'Apr 02, 2024',
    featured: false,
    tags: ['React', 'Web Dev', 'JavaScript'],
    readTime: '8 min read',
    status: 'published'
  },
  {
    id: '10',
    title: 'The Fundamentals of Linear Algebra',
    subject: 'Mathematics',
    topic: 'Linear Algebra',
    subtopic: 'Matrices',
    snippet: 'An introduction to vectors, matrices, and linear transformations, and their applications in computer graphics.',
    content: '<p>Linear algebra is central to almost all areas of mathematics and its applications. It deals with vector spaces and linear mappings between these spaces.</p>',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'David Hilbert' },
    date: 'Apr 18, 2024',
    featured: false,
    tags: ['Math', 'Algebra', 'Matrices'],
    readTime: '7 min read',
    status: 'published'
  },
  {
    id: '11',
    title: 'Demystifying Thermodynamics',
    subject: 'Physics',
    topic: 'Thermodynamics',
    subtopic: 'Laws',
    snippet: 'Learn the four laws of thermodynamics and how they govern energy transfer and the direction of physical processes.',
    content: '<p>Thermodynamics is the branch of physics that deals with heat, work, and temperature, and their relation to energy, radiation, and physical properties of matter.</p>',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=2094',
    author: { name: 'Lord Kelvin' },
    date: 'May 05, 2024',
    featured: false,
    tags: ['Physics', 'Thermodynamics', 'Energy'],
    readTime: '10 min read',
    status: 'published'
  },
  {
    id: '12',
    title: 'Introduction to Data Structures',
    subject: 'Computer Science',
    topic: 'Data Structures',
    subtopic: 'Basics',
    snippet: 'Explore essential data structures like arrays, linked lists, stacks, and queues, and when to use them.',
    content: '<p>A data structure is a specialized format for organizing, processing, retrieving and storing data. Choosing the right data structure can significantly impact performance.</p>',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Grace Hopper' },
    date: 'May 20, 2024',
    featured: false,
    tags: ['CS', 'Data Structures', 'Algorithms'],
    readTime: '9 min read',
    status: 'published'
  },
  {
    id: '13',
    title: 'The Magic of Number Theory',
    subject: 'Mathematics',
    topic: 'Number Theory',
    subtopic: 'Primes',
    snippet: 'Dive into the fascinating properties of prime numbers and their crucial role in modern cryptography.',
    content: '<p>Number theory is a branch of pure mathematics devoted primarily to the study of the integers and integer-valued functions. Prime numbers are its fundamental building blocks.</p>',
    image: 'https://images.unsplash.com/photo-1629858548982-fdb9d5e5b308?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Carl Friedrich Gauss' },
    date: 'Jun 10, 2024',
    featured: false,
    tags: ['Math', 'Number Theory', 'Cryptography'],
    readTime: '8 min read',
    status: 'published'
  },
  {
    id: '14',
    title: 'Cybersecurity Fundamentals',
    subject: 'Computer Science',
    topic: 'Security',
    subtopic: 'Basics',
    snippet: 'Understand the core concepts of cybersecurity, including encryption, firewalls, and common attack vectors.',
    content: '<p>Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information.</p>',
    image: 'https://images.unsplash.com/photo-1510511459019-5efa7ae57002?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'Bruce Schneier' },
    date: 'Jun 25, 2024',
    featured: false,
    tags: ['Security', 'Cybersecurity', 'IT'],
    readTime: '10 min read',
    status: 'published'
  },
  {
    id: '15',
    title: 'The Principles of Optics',
    subject: 'Physics',
    topic: 'Optics',
    subtopic: 'Light',
    snippet: 'Learn how light behaves, including reflection, refraction, diffraction, and the dual nature of light.',
    content: '<p>Optics is the branch of physics that studies the behaviour and properties of light, including its interactions with matter and the construction of instruments that use or detect it.</p>',
    image: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=2070',
    author: { name: 'James Clerk Maxwell' },
    date: 'Jul 05, 2024',
    featured: false,
    tags: ['Physics', 'Optics', 'Light'],
    readTime: '7 min read',
    status: 'published'
  }
];

export const categories = [
  { name: 'Computer Science', count: 7 },
  { name: 'Physics', count: 5 },
  { name: 'Mathematics', count: 3 }
];

export const learningPaths = [
  {
    id: '1',
    title: 'Introduction to Calculus',
    description: 'Learn the basics of limits, derivatives, and integrals.',
    postCount: 1
  },
  {
    id: '2',
    title: 'Frontend Web Development',
    description: 'Master HTML, CSS, and modern JavaScript frameworks.',
    postCount: 1
  },
  {
    id: '3',
    title: 'Theoretical Physics',
    description: 'Deep dive into quantum mechanics and relativity.',
    postCount: 2
  }
];
